name: Lint Code Base

on: [push]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_GO: false  # Disable due to a bug
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
